In [1]:
# https://math.stackexchange.com/questions/4431700/need-to-analytically-proof-a-fomula-for-variance-induction

import numpy as np


In [7]:
D4 = np.array([1, 2, 3, 2])
D5 = np.append(D4, [2])

In [10]:
print(D4)
print(D5)
print(np.var(D4))
print(np.var(D5))

[1 2 3 2]
[1 2 3 2 2]
0.5
0.4


In [25]:
def optA(n, var_prev, exp_prev, exp, new):
    var = (n-1)/n*var_prev + 1/n*(new - exp_prev)*(new - exp)
    return var

def optB(n, var_prev, exp_prev, exp, new):
    var = (n-1)/n*var_prev + 1/(n-1)*(new - exp_prev)*(new - exp)
    return var

def optC(n, var_prev, exp_prev, exp, new):
    var = (n-2)/(n-1)*var_prev + 1/n*(new - exp_prev)*(new - exp)
    return var

def optD(n, var_prev, exp_prev, exp, new):
    var = (n-1)/n*var_prev + 1/n*(new - exp_prev)**2
    return var


In [48]:
D_prev = np.array([1, 2, 3, 2])
new = 3
D = np.append(D_prev, np.array([new]))

var_prev = np.var(D_prev)
exp_prev = np.mean(D_prev)
var = np.var(D)
exp = np.mean(D)
n = D.size

print("D:", D, "var_prev:", var_prev, "exp_prev:", exp_prev, "exp:", exp, "new:", new, "var:", var)

print("A:", optA(n=n, var_prev=var_prev, exp_prev=exp_prev, exp=exp, new=new))
print("B:", optB(n=n, var_prev=var_prev, exp_prev=exp_prev, exp=exp, new=new))
print("C:", optC(n=n, var_prev=var_prev, exp_prev=exp_prev, exp=exp, new=new))
print("D:", optD(n=n, var_prev=var_prev, exp_prev=exp_prev, exp=exp, new=new))


D: [1 2 3 2 3] var_prev: 0.5 exp_prev: 2.0 exp: 2.2 new: 3 var: 0.5599999999999999
A: 0.56
B: 0.6
C: 0.5349999999999999
D: 0.6000000000000001


In [33]:
optA(n=5, var_prev=0.5, exp_prev=2, exp=2, new=2)

0.4

In [20]:
optB(n=5, var_prev=0.5, exp_prev=2, exp=2, new=2)

0.4

In [23]:
optC(n=5, var_prev=0.5, exp_prev=2, exp=2, new=2)

0.375

In [49]:
optD(n=5, var_prev=0.5, exp_prev=2, exp=2, new=2)

0.4

In [55]:
import numpy as np

def reshape(x):
    """return x_reshaped as the flatterned vector of the multi-dimensional array x"""
    x_reshaped = x.flatten()
    return x_reshaped

x_2d = np.array([
    [0, 1],
    [2, 3]
])

In [57]:
print("x_2d:\n", x_2d)

x_1d = reshape(x_2d)
print("x_1d:\n", x_1d)

print("x_1d:\n", np.reshape(x_2d, (-1,)))

x_2d:
 [[0 1]
 [2 3]]
x_1d:
 [0 1 2 3]
x_1d:
 [0 1 2 3]
