In [2]:
# Question 1:
# To determine whether (x^T)*A*y is positive definite, we need to get
# the eigenvalues of matrix A

import numpy as np
from numpy import linalg as la

A = np.array([
    [2, -1],
    [-1, 1]
])

vals, vecs = la.eig(A)
print(vals)
print(vecs)
# 
# as below, all the eigenvalues are positive
# therefore, the matrix is positive definite
# 
# [2.61803399 0.38196601]
# [[ 0.85065081  0.52573111]
#  [-0.52573111  0.85065081]]

[2.61803399 0.38196601]
[[ 0.85065081  0.52573111]
 [-0.52573111  0.85065081]]


In [3]:
# question 5
# For any two fectors, x, y, write a short peice of code that defines a valid inner product.

import numpy as np

def dot(a, b):
    """Compute dot product between a and b.
    Args:
      a, b: (2,) ndarray as R^2 vectors
      
    Returns:
      a number which is the dot produt between a, b
    """
    
    # dot_product = a[0]*b[0] + a[1]*b[1]
    dot_product = np.dot(a, b)
    
    return dot_product

In [4]:
# Test your code:

a = np.array([1, 0])
b = np.array([0, 1])

print(dot(a,b))


0


In [5]:
# quiz:
np.sqrt(5)

2.23606797749979

In [9]:
A = np.array([
    [1, 2],
    [3, 4]
])
print(A)
# iterate over all columns of a matrix
for column in A.T:
    print(column)

for i in range(10):
    print(i)


[[1 2]
 [3 4]]
[1 3]
[2 4]
0
1
2
3
4
5
6
7
8
9
