In [7]:
import numpy as np

x = np.transpose(np.array([[1, 1]]))
y = np.transpose(np.array([[-1, 1]]))

print(x)
print(y)

[[1]
 [1]]
[[-1]
 [ 1]]


In [9]:
A = np.array([
    [2, -1],
    [-1, 4]
])
print(A)

[[ 2 -1]
 [-1  4]]


In [11]:
dot_prod = np.transpose(x) @ A @ y
print(dot_prod)

[[2]]


In [14]:
cos_val = dot_prod / (np.linalg.norm(x) * np.linalg.norm(y))
print(cos_val)

[[1.]]


In [16]:
print(np.arccos(cos_val))

[[2.10734243e-08]]


In [17]:
np.cos(1.2)

0.3623577544766736

In [20]:
cos_val_naive = 2 / (2 * 2*np.sqrt(2))
print(cos_val_naive)

0.35355339059327373


In [22]:
print(np.arccos(cos_val_naive))

1.2094292028881888


In [26]:
import numpy as np

a_origin = np.array([5,4])

a = a_origin[np.newaxis]
print(a)
print(a.T)

[[5 4]]
[[5]
 [4]]


In [28]:
def inner_product(x, y, A):
    x = x[np.newaxis].T
    y = y[np.newaxis].T
    prod = x.T @ A @ y
    return prod

# Test
x = np.array([1, 1])
y = np.array([-1, 1])
A = np.array([
    [2, -1],
    [-1, 4]
])

print(inner_product(x, y, A))

[[2]]


In [34]:
x = np.array([0, -1])
y = np.array([1, 1])
A = np.array([
    [1, -1/2],
    [-1/2, 5]
])

print("eigen A:", np.linalg.eig(A))

cos_val = inner_product(x, y, A) / np.sqrt(inner_product(x,x,A)*inner_product(y,y,A))
print("cos_val:", cos_val)
print(np.arccos(cos_val))

eigen A: (array([0.93844719, 5.06155281]), array([[-0.99250756,  0.12218326],
       [-0.12218326, -0.99250756]]))
cos_val: [[-0.9]]
[[2.69056584]]


In [36]:
x = np.array([2, 2])
y = np.array([-2, -2])
A = np.array([
    [2, 1],
    [1, 4]
])

cos_val = inner_product(x, y, A) / np.sqrt(inner_product(x,x,A)*inner_product(y,y,A))
print("cos_val:", cos_val)
print(np.arccos(cos_val))

cos_val: [[-1.]]
[[3.14159265]]


In [38]:
x = np.array([1, 1])
y = np.array([1, -1])
A = np.array([
    [1, 0],
    [0, 5]
])

cos_val = inner_product(x, y, A) / np.sqrt(inner_product(x,x,A)*inner_product(y,y,A))
print("cos_val:", cos_val)
print(np.arccos(cos_val))

cos_val: [[-0.66666667]]
[[2.30052398]]


In [40]:
x = np.array([1, 1, 1])
y = np.array([2, -1, 0])
A = np.array([
    [1, 0, 0],
    [0, 2, -1],
    [0, -1, 3]
])

cos_val = inner_product(x, y, A) / np.sqrt(inner_product(x,x,A)*inner_product(y,y,A))
print("cos_val:", cos_val)
print(np.arccos(cos_val))

cos_val: [[0.20412415]]
[[1.3652274]]


In [44]:
x = np.array([1, 1])
y = np.array([-1, 1])
A = np.array([
    [2, 0],
    [0, 1]
])

cos_val = inner_product(x,y,A) / np.sqrt(inner_product(x,x,A)*inner_product(y,y,A))
print("cos_val:", cos_val)
rad = np.arccos(cos_val)
deg = np.degrees(rad)
print("rad:", rad)
print("deg:", deg)


cos_val: [[-0.33333333]]
rad: [[1.91063324]]
deg: [[109.47122063]]
